import { type FormEvent, useState } from "react";
import { Qr } from "./Qr.tsx";
import {
  SEED_ENTROPY_BYTES,
  decodePsbt,
  decodeSeed,
  encodePsbtParts,
  encodeSeed,
  parseHex,
  randomBytes,
  toHex,
} from "./playground.ts";

function messageOf(e: unknown): string {
  return e instanceof Error ? e.message : "failed";
}

export function App() {
  return (
    <main>
      <h1>UR playground</h1>
      <p className="lede">
        Local <code>ur:seed</code> and <code>ur:psbt</code> encode/decode. Nothing is sent.
        Generated bytes are not a wallet.
      </p>
      <SeedPanel />
      <PsbtPanel />
    </main>
  );
}

function SeedPanel() {
  const [hex, setHex] = useState("");
  const [ur, setUr] = useState("");
  const [decoded, setDecoded] = useState("");
  const [error, setError] = useState("");

  function generate() {
    setError("");
    setHex(toHex(randomBytes(SEED_ENTROPY_BYTES)));
  }

  function encode(e: FormEvent) {
    e.preventDefault();
    setError("");
    try {
      setUr(encodeSeed(parseHex(hex)));
    } catch (err) {
      setUr("");
      setError(messageOf(err));
    }
  }

  function decode(e: FormEvent) {
    e.preventDefault();
    setError("");
    try {
      setDecoded(toHex(decodeSeed(ur)));
    } catch (err) {
      setDecoded("");
      setError(messageOf(err));
    }
  }

  return (
    <section>
      <h2>Seed</h2>
      <form onSubmit={encode}>
        <label htmlFor="seed-hex">Entropy hex</label>
        <textarea
          id="seed-hex"
          rows={2}
          spellCheck={false}
          value={hex}
          onChange={(e) => setHex(e.target.value)}
        />
        <div className="row">
          <button type="button" onClick={generate}>
            Generate 16 bytes
          </button>
          <button type="submit">Encode ur:seed</button>
        </div>
      </form>
      {ur !== "" ? (
        <div className="result">
          <Qr value={ur} label="ur:seed" />
          <pre>{ur}</pre>
        </div>
      ) : null}
      <form onSubmit={decode}>
        <label htmlFor="seed-ur">Paste UR</label>
        <textarea
          id="seed-ur"
          rows={3}
          spellCheck={false}
          value={ur}
          onChange={(e) => setUr(e.target.value)}
        />
        <button type="submit">Decode</button>
      </form>
      {decoded !== "" ? <pre>{decoded}</pre> : null}
      {error !== "" ? <p className="error">{error}</p> : null}
    </section>
  );
}

function PsbtPanel() {
  const [hex, setHex] = useState("");
  const [parts, setParts] = useState<string[]>([]);
  const [urText, setUrText] = useState("");
  const [decoded, setDecoded] = useState("");
  const [error, setError] = useState("");

  function encode(e: FormEvent) {
    e.preventDefault();
    setError("");
    try {
      const next = encodePsbtParts(parseHex(hex));
      setParts(next);
      setUrText(next.join("\n"));
    } catch (err) {
      setParts([]);
      setUrText("");
      setError(messageOf(err));
    }
  }

  function decode(e: FormEvent) {
    e.preventDefault();
    setError("");
    try {
      setDecoded(toHex(decodePsbt(urText)));
    } catch (err) {
      setDecoded("");
      setError(messageOf(err));
    }
  }

  return (
    <section>
      <h2>PSBT</h2>
      <form onSubmit={encode}>
        <label htmlFor="psbt-hex">PSBT hex</label>
        <textarea
          id="psbt-hex"
          rows={6}
          spellCheck={false}
          value={hex}
          onChange={(e) => setHex(e.target.value)}
        />
        <button type="submit">Encode ur:psbt (maxFragmentLength 50)</button>
      </form>
      {parts.length > 0 ? (
        <ol className="parts">
          {parts.map((part, i) => (
            <li key={part}>
              <Qr value={part} label={`${i + 1}/${parts.length}`} />
              <pre>{part}</pre>
            </li>
          ))}
        </ol>
      ) : null}
      <form onSubmit={decode}>
        <label htmlFor="psbt-ur">Paste UR parts</label>
        <textarea
          id="psbt-ur"
          rows={6}
          spellCheck={false}
          value={urText}
          onChange={(e) => setUrText(e.target.value)}
        />
        <button type="submit">Decode</button>
      </form>
      {decoded !== "" ? <pre>{decoded}</pre> : null}
      {error !== "" ? <p className="error">{error}</p> : null}
    </section>
  );
}
