name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: qntx/workflows/.github/workflows/ci-bun.yml@v2
    permissions:
      contents: read
